export const mockData = [
  {
    "Farmer Name": "Ramesh Kumar",
    "Village": "Sembanur",
    "Taluk": "Thiruvidaimarudur",
    "Acre": 2.5,
    "Expected Quantity (MT)": 5.0,
    "Assigned To": "Vijay",
    "Procurement Status": "Confirmed",
    "Confirm": "Yes",
    "Heritage": "Organic",
    "Purchased Year": 2023,
    "Status": "Active",
    "To Be Confirmed On": "",
    "Seed Company": "Kaveri Seeds",
    "Sowing Date": "2024-05-10",
    "Direct Sowing / Transplant": "Transplant",
    "Transplant Date": "2024-06-01",
    "Weedicide": "2024-06-15",
    "1st Dose Date": "2024-06-20",
    "2nd Dose Date": "2024-07-15",
    "3rd Dose Date": "",
    "Plant Protection": "2024-07-20",
    "Expected Harvest Date": "2024-09-10"
  },
  {
    "Farmer Name": "Kannan S",
    "Village": "Sembanur",
    "Taluk": "Thiruvidaimarudur",
    "Acre": 3.0,
    "Expected Quantity (MT)": 6.5,
    "Assigned To": "Vijay",
    "Procurement Status": "Pending",
    "Confirm": "No",
    "Heritage": "Conventional",
    "Purchased Year": 2022,
    "Status": "Active",
    "To Be Confirmed On": "2024-06-05",
    "Seed Company": "Pioneer",
    "Sowing Date": "2024-05-15",
    "Direct Sowing / Transplant": "Direct Sowing",
    "Transplant Date": "",
    "Weedicide": "2024-06-02",
    "1st Dose Date": "2024-06-10",
    "2nd Dose Date": "2024-07-05",
    "3rd Dose Date": "2024-08-01",
    "Plant Protection": "2024-07-25",
    "Expected Harvest Date": "2024-09-20"
  },
  {
    "Farmer Name": "Murugan G",
    "Village": "Kumbakonam Rural",
    "Taluk": "Kumbakonam",
    "Acre": 1.5,
    "Expected Quantity (MT)": 3.0,
    "Assigned To": "Prabu",
    "Procurement Status": "Confirmed",
    "Confirm": "Yes",
    "Heritage": "Conventional",
    "Purchased Year": 2023,
    "Status": "Active",
    "To Be Confirmed On": "",
    "Seed Company": "Mahyco",
    "Sowing Date": "2024-05-20",
    "Direct Sowing / Transplant": "Transplant",
    "Transplant Date": "2024-06-10",
    "Weedicide": "2024-06-25",
    "1st Dose Date": "2024-07-01",
    "2nd Dose Date": "2024-07-20",
    "3rd Dose Date": "",
    "Plant Protection": "2024-08-05",
    "Expected Harvest Date": "2024-09-25"
  },
  {
    "Farmer Name": "Selvam T",
    "Village": "Veppathur",
    "Taluk": "Thiruvidaimarudur",
    "Acre": 4.0,
    "Expected Quantity (MT)": 8.0,
    "Assigned To": "Vijay",
    "Procurement Status": "TBD",
    "Confirm": "No",
    "Heritage": "Organic",
    "Purchased Year": 2024,
    "Status": "Inactive",
    "To Be Confirmed On": "2024-06-15",
    "Seed Company": "",
    "Sowing Date": "",
    "Direct Sowing / Transplant": "",
    "Transplant Date": "",
    "Weedicide": "",
    "1st Dose Date": "",
    "2nd Dose Date": "",
    "3rd Dose Date": "",
    "Plant Protection": "",
    "Expected Harvest Date": ""
  },
  {
    "Farmer Name": "Dinesh M",
    "Village": "Swamimalai",
    "Taluk": "Kumbakonam",
    "Acre": 2.0,
    "Expected Quantity (MT)": 4.2,
    "Assigned To": "Karthik",
    "Procurement Status": "Confirmed",
    "Confirm": "Yes",
    "Heritage": "Conventional",
    "Purchased Year": 2021,
    "Status": "Active",
    "To Be Confirmed On": "",
    "Seed Company": "Nuziveedu",
    "Sowing Date": "2024-05-25",
    "Direct Sowing / Transplant": "Direct Sowing",
    "Transplant Date": "",
    "Weedicide": "2024-06-15",
    "1st Dose Date": "2024-06-20",
    "2nd Dose Date": "2024-07-10",
    "3rd Dose Date": "2024-08-05",
    "Plant Protection": "2024-08-10",
    "Expected Harvest Date": "2024-10-05"
  }
];
